name: Update Graph on CSV Change

on:
  push:
    paths:
      - 'myoho_shugohi.csv'

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウト
      uses: actions/checkout@v3

    - name: Python セットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 依存パッケージをインストール
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib

    - name: グラフ画像を生成
      run: python generate_graph.py

    - name: 変更をコミット＆プッシュ
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add graph.png
        git commit -m "Auto-update graph from myoho_shugohi.csv" || echo "No changes"
        git push
